<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYC1221031" failures="0" tests="4" name="RunnerFile.TestNGRunnerFile" time="39.531" errors="1" timestamp="2024-01-24T17:45:15 IST" skipped="0">
  <testcase classname="RunnerFile.TestNGRunnerFile" name="runScenario" time="16.681"/>
  <system-out/>
  <testcase classname="RunnerFile.TestNGRunnerFile" name="runScenario" time="3.764">
    <error message="&quot;user enters valid username &quot;admin&quot; and valid pwd &quot;admin&quot;&quot; matches more than one step definition:
  &quot;^user enters valid username (.+) and valid pwd (.+)$&quot; in stepDefination.LoginTest.user_enters_valid_username_admin1_and_valid_pwd_admin(java.lang.String,java.lang.String)
  &quot;user enters valid username {string} and valid pwd {string}&quot; in stepDefination.LoginTest.user_enters_valid_username_and_valid_pwd(java.lang.String,java.lang.String)" type="io.cucumber.core.runner.AmbiguousStepDefinitionsException">
      <![CDATA[io.cucumber.core.runner.AmbiguousStepDefinitionsException: "user enters valid username "admin" and valid pwd "admin"" matches more than one step definition:
  "^user enters valid username (.+) and valid pwd (.+)$" in stepDefination.LoginTest.user_enters_valid_username_admin1_and_valid_pwd_admin(java.lang.String,java.lang.String)
  "user enters valid username {string} and valid pwd {string}" in stepDefination.LoginTest.user_enters_valid_username_and_valid_pwd(java.lang.String,java.lang.String)
at io.cucumber.core.runner.CachingGlue.findStepDefinitionMatch(CachingGlue.java:402)
at io.cucumber.core.runner.CachingGlue.stepDefinitionMatch(CachingGlue.java:370)
at io.cucumber.core.runner.Runner.matchStepToStepDefinition(Runner.java:183)
at io.cucumber.core.runner.Runner.createTestStepsForPickleSteps(Runner.java:163)
at io.cucumber.core.runner.Runner.createTestCaseForPickle(Runner.java:146)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:74)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="RunnerFile.TestNGRunnerFile" name="runScenario" time="8.627"/>
  <system-out/>
  <testcase classname="RunnerFile.TestNGRunnerFile" name="runScenario" time="10.459"/>
  <system-out/>
</testsuite> <!-- RunnerFile.TestNGRunnerFile -->
